import { ExecArgs } from "@medusajs/framework/types"
import { AFFILIATE_MODULE } from "../modules/affiliate"
import AffiliateService from "../modules/affiliate/service"
import * as bcrypt from "bcryptjs"

export default async function promoteAdmin({ container }: ExecArgs) {
    const affiliateService: AffiliateService = container.resolve(AFFILIATE_MODULE)

    const email = "textsence.ai@gmail.com"
    const password = "Aa123456@"
    const targetRole = "admin"

    console.log(`Processing admin promotion for: ${email}`)

    const existing = await affiliateService.listAffiliates({ email })

    if (existing.length > 0) {
        const affiliate = existing[0]
        console.log(`Affiliate found (ID: ${affiliate.id}). Promoting to admin...`)

        await affiliateService.updateAffiliates([{
            id: affiliate.id,
            role: targetRole,
            status: 'active'
        }])

        console.log("Successfully updated existing affiliate to Admin.")
    } else {
        console.log("Affiliate not found. Creating new Admin account...")

        const password_hash = await bcrypt.hash(password, 10)

        // Create new affiliate
        // Note: We use the service's create method if available or standard create pattern
        // Attempting to use standard createAffiliates method generated by MedusaService
        const newAffiliate = await affiliateService.createAffiliates([{
            email,
            password_hash,
            first_name: "Admin",
            last_name: "User",
            code: "ADMIN-" + Math.random().toString(36).substring(7).toUpperCase(),
            role: targetRole,
            status: 'active',
            commission_rate: 0.2
        }])

        console.log(`Successfully created new Admin affiliate (ID: ${newAffiliate[0].id}).`)
    }
}
