import { MedusaRequest, MedusaResponse } from "@medusajs/framework/http"
import { AFFILIATE_MODULE } from "../../../../modules/affiliate"
import AffiliateService from "../../../../modules/affiliate/service"
import { getAffiliateFromRequest } from "../../../../utils/affiliate-auth"

export async function GET(
    req: MedusaRequest,
    res: MedusaResponse
) {
    try {
        const affiliateAuth = getAffiliateFromRequest(req)
        if (!affiliateAuth) {
            return res.status(401).json({ message: "Unauthorized" })
        }

        const affiliateService: AffiliateService = req.scope.resolve(AFFILIATE_MODULE)
        const currentAffiliate = await affiliateService.retrieveAffiliate(affiliateAuth.id)

        // Admin Role Check
        if (currentAffiliate.role !== 'admin') {
            return res.status(403).json({ message: "Forbidden: Admin access required" })
        }

        // List all affiliates
        // Using listAndCountAffiliates generated by MedusaService
        const [affiliates, count] = await affiliateService.listAndCountAffiliates({}, {
            take: 100, // Hard limit for MVP
            order: { created_at: 'DESC' }
        })

        res.json({
            affiliates,
            count,
            offset: 0,
            limit: 100
        })
    } catch (error) {
        console.error('[Admin List API] Error:', error)
        res.status(500).json({ message: "Internal Server Error" })
    }
}
